// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzjzkscqnnhxwlnpgbdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16anprc2Nxbm5oeHdsbnBnYmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzkzOTAsImV4cCI6MjA3MjIxNTM5MH0.PsB_zatjbFCPW603uqGxAKSGi_w0vB4bm8_JKMCzL1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});